// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Title field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Copyright field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.copyright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    copyright: prismicT.RichTextField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HeroHeaderSlice | FreeTextSectionSlice | TextSliderSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = NavLinkSlice | SocialLinkSlice;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
/** Content for Post Index documents */
interface PostIndexDocumentData {
    /**
     * Title field in *Post Index*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post_index.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Document Title field in *Post Index*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post_index.document_title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    document_title: prismicT.KeyTextField;
    /**
     * Document Description field in *Post Index*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post_index.document_description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    document_description: prismicT.KeyTextField;
}
/**
 * Post Index document from Prismic
 *
 * - **API ID**: `post_index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostIndexDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<PostIndexDocumentData>, "post_index", Lang>;
/** Content for Post documents */
interface PostDocumentData {
    /**
     * Type field in *Post*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: post.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    type: prismicT.SelectField<"scala" | "java" | "typescript">;
    /**
     * Title field in *Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Snippet field in *Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post.snippet
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    snippet: prismicT.RichTextField;
    /**
     * Published At field in *Post*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: post.published_at
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    published_at: prismicT.DateField;
    /**
     * Body field in *Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post.body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;
/** Content for Project Index documents */
interface ProjectIndexDocumentData {
    /**
     * Title field in *Project Index*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_index.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Project Index document from Prismic
 *
 * - **API ID**: `project_index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectIndexDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ProjectIndexDocumentData>, "project_index", Lang>;
/** Content for Project documents */
interface ProjectDocumentData {
    /**
     * Image field in *Project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Title field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Snippet field in *Project*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.snippet
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    snippet: prismicT.RichTextField;
    /**
     * Published At field in *Project*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: project.published_at
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    published_at: prismicT.TimestampField;
    /**
     * Body field in *Project*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
export type AllDocumentTypes = FooterDocument | HomepageDocument | NavigationDocument | PostIndexDocument | PostDocument | ProjectIndexDocument | ProjectDocument;
/**
 * Primary content in FreeTextSection → Primary
 *
 */
interface FreeTextSectionSliceDefaultPrimary {
    /**
     * Title field in *FreeTextSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: free_text_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Body field in *FreeTextSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: free_text_section.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Default variation for FreeTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FreeTextSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FreeTextSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FreeTextSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *FreeTextSection*
 *
 */
type FreeTextSectionSliceVariation = FreeTextSectionSliceDefault;
/**
 * FreeTextSection Shared Slice
 *
 * - **API ID**: `free_text_section`
 * - **Description**: `FreeTextSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FreeTextSectionSlice = prismicT.SharedSlice<"free_text_section", FreeTextSectionSliceVariation>;
/**
 * Primary content in HeroHeader → Primary
 *
 */
interface HeroHeaderSliceDefaultPrimary {
    /**
     * Title field in *HeroHeader → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_header.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *HeroHeader → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_header.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for HeroHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroHeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroHeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeroHeader*
 *
 */
type HeroHeaderSliceVariation = HeroHeaderSliceDefault;
/**
 * HeroHeader Shared Slice
 *
 * - **API ID**: `hero_header`
 * - **Description**: `HeroHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroHeaderSlice = prismicT.SharedSlice<"hero_header", HeroHeaderSliceVariation>;
/**
 * Item in NavLink → Items
 *
 */
export interface NavLinkSliceDefaultItem {
    /**
     * Label field in *NavLink → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: nav_link.items[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Path field in *NavLink → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: nav_link.items[].path
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    path: prismicT.KeyTextField;
}
/**
 * Default variation for NavLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NavLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavLinkSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<NavLinkSliceDefaultItem>>;
/**
 * Slice variation for *NavLink*
 *
 */
type NavLinkSliceVariation = NavLinkSliceDefault;
/**
 * NavLink Shared Slice
 *
 * - **API ID**: `nav_link`
 * - **Description**: `NavLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavLinkSlice = prismicT.SharedSlice<"nav_link", NavLinkSliceVariation>;
/**
 * Item in SocialLink → Items
 *
 */
export interface SocialLinkSliceDefaultItem {
    /**
     * Type field in *SocialLink → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: social_link.items[].type
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    type: prismicT.SelectField<"github" | "twitter" | "linkedin">;
    /**
     * Path field in *SocialLink → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: social_link.items[].path
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    path: prismicT.LinkField;
}
/**
 * Default variation for SocialLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SocialLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialLinkSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<SocialLinkSliceDefaultItem>>;
/**
 * Slice variation for *SocialLink*
 *
 */
type SocialLinkSliceVariation = SocialLinkSliceDefault;
/**
 * SocialLink Shared Slice
 *
 * - **API ID**: `social_link`
 * - **Description**: `SocialLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialLinkSlice = prismicT.SharedSlice<"social_link", SocialLinkSliceVariation>;
/**
 * Item in TextSlider → Items
 *
 */
export interface TextSliderSliceDefaultItem {
    /**
     * Text field in *TextSlider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_slider.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
}
/**
 * Default variation for TextSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliderSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<TextSliderSliceDefaultItem>>;
/**
 * Slice variation for *TextSlider*
 *
 */
type TextSliderSliceVariation = TextSliderSliceDefault;
/**
 * TextSlider Shared Slice
 *
 * - **API ID**: `text_slider`
 * - **Description**: `TextSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliderSlice = prismicT.SharedSlice<"text_slider", TextSliderSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { FooterDocumentData, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavigationDocumentData, NavigationDocumentDataSlicesSlice, NavigationDocument, PostIndexDocumentData, PostIndexDocument, PostDocumentData, PostDocument, ProjectIndexDocumentData, ProjectIndexDocument, ProjectDocumentData, ProjectDocument, AllDocumentTypes, FreeTextSectionSliceDefaultPrimary, FreeTextSectionSliceDefault, FreeTextSectionSliceVariation, FreeTextSectionSlice, HeroHeaderSliceDefaultPrimary, HeroHeaderSliceDefault, HeroHeaderSliceVariation, HeroHeaderSlice, NavLinkSliceDefaultItem, NavLinkSliceDefault, NavLinkSliceVariation, NavLinkSlice, SocialLinkSliceDefaultItem, SocialLinkSliceDefault, SocialLinkSliceVariation, SocialLinkSlice, TextSliderSliceDefaultItem, TextSliderSliceDefault, TextSliderSliceVariation, TextSliderSlice };
    }
}
