// Code generated by Slice Machine. DO NOT EDIT.

import FreeTextSection from './FreeTextSection';
import HeroHeader from './HeroHeader';

export {
	FreeTextSection,
	HeroHeader,
};

export const components = {
	free_text_section: FreeTextSection,
	hero_header: HeroHeader,
};
