// Code generated by Slice Machine. DO NOT EDIT.

import FreeTextSection from './FreeTextSection';
import HeroHeader from './HeroHeader';
import TextSlider from './TextSlider';

export {
	FreeTextSection,
	HeroHeader,
	TextSlider,
};

export const components = {
	free_text_section: FreeTextSection,
	hero_header: HeroHeader,
	text_slider: TextSlider,
};
